In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

In [3]:
dataset = pd.read_csv('titanic.csv')
display(dataset)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
data = pd.DataFrame(dataset[['Sex', 'Age', 'Pclass', 'Fare', 'Survived']])
pos_missing_train = data[data.isnull().any(axis=1)].index.tolist()
display(data)
print(pos_missing_train)

        Sex   Age  Pclass     Fare  Survived
0      male  22.0       3   7.2500         0
1    female  38.0       1  71.2833         1
2    female  26.0       3   7.9250         1
3    female  35.0       1  53.1000         1
4      male  35.0       3   8.0500         0
..      ...   ...     ...      ...       ...
886    male  27.0       2  13.0000         0
887  female  19.0       1  30.0000         1
888  female   NaN       3  23.4500         0
889    male  26.0       1  30.0000         1
890    male  32.0       3   7.7500         0

[891 rows x 5 columns]

[5, 17, 19, 26, 28, 29, 31, 32, 36, 42, 45, 46, 47, 48, 55, 64, 65, 76, 77, 82, 87, 95, 101, 107, 109, 121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837, 839, 846, 849, 859, 863, 868, 878, 888]

In [5]:
train_data = pd.DataFrame(data[['Sex', 'Pclass', 'Fare', 'Survived']])
train_data = train_data.loc[~train_data.index.isin(pos_missing_train)]
display(train_data)

        Sex  Pclass     Fare  Survived
0      male       3   7.2500         0
1    female       1  71.2833         1
2    female       3   7.9250         1
3    female       1  53.1000         1
4      male       3   8.0500         0
..      ...     ...      ...       ...
885  female       3  29.1250         0
886    male       2  13.0000         0
887  female       1  30.0000         1
889    male       1  30.0000         1
890    male       3   7.7500         0

[714 rows x 4 columns]

In [6]:
train_label = pd.DataFrame(data[['Age']])
train_label = train_label.loc[~train_label.index.isin(pos_missing_train)]
display(train_label)

      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
885  39.0
886  27.0
887  19.0
889  26.0
890  32.0

[714 rows x 1 columns]

In [7]:
test_data = pd.DataFrame(data[['Sex', 'Pclass', 'Fare', 'Survived']])
test_data = test_data.iloc[pos_missing_train]
display(test_data)

        Sex  Pclass     Fare  Survived
5      male       3   8.4583         0
17     male       2  13.0000         1
19   female       3   7.2250         1
26     male       3   7.2250         0
28   female       3   7.8792         1
..      ...     ...      ...       ...
859    male       3   7.2292         0
863  female       3  69.5500         0
868    male       3   9.5000         0
878    male       3   7.8958         0
888  female       3  23.4500         0

[177 rows x 4 columns]

In [8]:
def minmax(data):
    min = 0
    max = 1
    minval = data.min()
    maxval = data.max()
    data = (data - minval) * (max - min) / (maxval - minval) + min
    return data

minPclass = train_data['Pclass'].min()
maxPclass = train_data['Pclass'].max()
minFare = train_data['Fare'].min()
maxFare = train_data['Fare'].max()

dataPclass = train_data['Pclass']
dataFare = train_data['Fare']

train_data['Pclass'] = minmax(dataPclass)
train_data['Fare'] = minmax(dataFare)

display(train_data)

        Sex  Pclass      Fare  Survived
0      male     1.0  0.014151         0
1    female     0.0  0.139136         1
2    female     1.0  0.015469         1
3    female     0.0  0.103644         1
4      male     1.0  0.015713         0
..      ...     ...       ...       ...
885  female     1.0  0.056848         0
886    male     0.5  0.025374         0
887  female     0.0  0.058556         1
889    male     0.0  0.058556         1
890    male     1.0  0.015127         0

[714 rows x 4 columns]

In [9]:
def minmax_test(data, minval, maxval):
    min = 0
    max = 1
    data = (data - minval) * (max - min) / (maxval - minval) + min
    return data

dataPclass = test_data['Pclass']
dataFare = test_data['Fare']

test_data['Pclass'] = minmax_test(dataPclass, minPclass, maxPclass)
test_data['Fare'] = minmax_test(dataFare, minFare, maxFare)

display(test_data)

        Sex  Pclass      Fare  Survived
5      male     1.0  0.016510         0
17     male     0.5  0.025374         1
19   female     1.0  0.014102         1
26     male     1.0  0.014102         0
28   female     1.0  0.015379         1
..      ...     ...       ...       ...
859    male     1.0  0.014110         0
863  female     1.0  0.135753         0
868    male     1.0  0.018543         0
878    male     1.0  0.015412         0
888  female     1.0  0.045771         0

[177 rows x 4 columns]

In [10]:
label_encoder = LabelEncoder()
train_label_encoded = label_encoder.fit_transform(train_label)

train_data[train_data.columns[0]] = LabelEncoder().fit_transform(train_data['Sex'])

kNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
kNN.fit(train_data, train_label_encoded)

class_result = kNN.predict(train_data)

class_result = label_encoder.inverse_transform(class_result)

display(class_result)

/home/ex-dec/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([22.  , 38.  , 17.  , 33.  , 20.  , 54.  ,  2.  ,  1.  , 14.  ,
        4.  , 58.  , 20.  ,  4.  , 14.  , 55.  ,  2.  , 18.  , 34.  ,
       31.  , 15.  , 28.  ,  3.  ,  5.  , 19.  , 40.  , 24.  , 28.  ,
       31.  , 20.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        1.  , 21.  , 49.  , 29.  , 65.  , 17.  , 17.  ,  5.  ,  1.  ,
       17.  , 38.  , 45.  ,  4.  , 17.  , 19.  , 17.  , 17.  , 24.  ,
       16.  , 21.  , 26.  , 32.  , 19.  ,  0.83,  5.  , 22.  , 29.  ,
       28.  , 17.  , 24.  , 16.  , 23.  , 20.  , 20.  , 18.  , 46.  ,
       26.  , 22.  , 71.  , 23.  ,  4.  , 34.  , 28.  , 21.  , 33.  ,
       21.  , 28.  , 21.  , 28.  , 31.  , 14.5 , 20.  , 20.  , 17.  ,
       21.  , 40.5 , 34.  , 24.  ,  2.  , 21.  , 32.5 , 32.  , 21.  ,
       12.  , 24.  , 45.  , 28.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 19.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       21.  ,  9.  , 34.  , 25.  , 51.  , 22.  , 20.  , 19.  , 51.  ,
       16.  , 20.  , 21.  , 40.  , 19.  , 17.  ,  1.  ,  9.  ,  2.  ,
       28.  , 61.  ,  2.  ,  1.  , 21.  , 56.  , 18.  , 50.  , 25.  ,
       19.  ,  9.  ,  1.  ,  4.  , 34.  , 40.  , 28.  , 32.  , 25.  ,
       19.  ,  2.  , 44.  , 58.  , 42.  , 24.  , 28.  , 18.  , 30.  ,
       16.  ,  2.  , 28.  , 26.  , 22.  , 40.  , 20.  , 30.  , 22.  ,
       25.  , 23.  , 17.  , 42.  , 32.  , 24.  , 16.  , 25.  , 20.  ,
       38.  , 22.  , 19.  , 22.  , 25.  , 35.  , 19.  , 28.  ,  5.  ,
       24.  , 34.  ,  7.  , 24.  , 33.  , 24.  , 17.  , 30.  , 44.  ,
       18.  , 24.  , 37.  , 34.  ,  2.  , 62.  , 21.  , 41.  , 29.  ,
       16.  , 35.  , 29.  ,  3.  , 52.  , 38.  , 24.  ,  1.  , 25.  ,
       40.  , 35.  , 25.  , 13.  , 37.  , 21.  , 21.  ,  2.  , 35.  ,
       40.5 , 18.  , 28.  , 16.  , 17.  , 29.  , 28.  , 31.  , 22.  ,
       26.  , 19.  , 36.  , 24.  , 28.  , 17.  ,  2.  , 50.  , 19.  ,
        0.92, 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 31.  ,
       19.  , 29.  , 54.  , 31.  , 40.  , 22.  , 28.  , 30.  , 22.  ,
       35.  , 61.  , 32.  , 31.  , 16.  , 45.5 , 38.  , 16.  , 29.  ,
       40.  , 16.  , 45.  ,  2.  , 23.  , 25.  , 25.  , 25.  , 32.  ,
       32.  ,  3.  , 17.  , 20.  , 17.  , 25.  , 28.  , 22.  , 24.  ,
        4.  , 29.  , 14.5 , 20.  , 22.  , 60.  , 24.  , 25.  , 18.  ,
       20.  , 22.  ,  3.  , 22.  , 27.  , 20.  , 19.  , 18.  ,  1.  ,
       21.  , 35.  , 21.  ,  1.  , 32.  , 17.  , 11.  , 21.  , 21.  ,
       23.  ,  4.  , 18.  , 14.  , 34.  , 24.  , 28.  , 20.  , 20.  ,
       20.  , 28.  , 20.  , 34.  , 40.5 ,  0.83, 19.  , 33.  , 20.  ,
       34.  , 32.  , 25.  , 10.  , 21.  , 29.  , 28.  , 18.  , 29.  ,
       29.  , 16.  , 34.  , 29.  , 17.  , 50.  , 14.  ,  9.  , 24.  ,
       19.  , 24.  ,  7.  , 28.  , 19.  , 32.  ,  4.  , 13.  , 34.  ,
        0.75, 27.  , 36.  , 30.  , 49.  , 29.  , 62.  , 17.  , 34.  ,
       20.  , 47.  , 25.  , 20.  , 62.  ,  0.75, 17.  ,  5.  , 23.  ,
       22.  , 34.  , 29.  , 22.  ,  2.  ,  1.  , 20.  , 63.  , 25.  ,
       33.  , 37.  , 20.  ,  3.  , 22.  , 55.  , 71.  , 20.  , 52.  ,
        2.  , 18.  , 17.  , 21.  , 37.  , 16.  , 18.  , 29.  , 28.  ,
       32.  , 29.  , 35.  , 54.  , 24.  , 47.  , 17.  , 29.  , 28.  ,
       30.  , 28.  , 16.  , 40.5 , 17.  , 21.  , 18.  , 29.  , 17.  ,
       20.  ,  7.  , 62.  , 30.  , 22.  , 36.  ,  2.  ,  2.  ,  2.  ,
       50.  , 64.  , 29.  , 33.  ,  8.  , 17.  , 34.  , 22.  , 22.  ,
       62.  , 48.  , 18.  , 36.  , 28.  , 28.  , 24.  , 28.  ,  3.  ,
       32.  , 19.  , 53.  , 36.  , 20.  , 19.  , 32.  , 39.  , 20.  ,
       25.  , 39.  , 34.  , 36.  , 18.  , 47.  , 60.  , 20.  , 17.  ,
       52.  , 22.  , 34.  , 24.  , 19.  , 49.  , 24.  , 20.  , 34.  ,
       36.  , 28.  , 27.  ,  3.  , 40.  ,  2.  , 20.  , 24.  , 34.  ,
       26.  ,  4.  , 24.  , 26.  , 37.  , 20.  , 18.  , 21.  , 61.  ,
       57.  , 21.  , 28.  , 26.  , 17.  , 27.  ,  2.  , 32.  , 21.  ,
       31.  , 41.  , 18.  , 24.  ,  2.  ,  0.75, 27.  , 28.  , 28.  ,
       23.  ,  4.  , 21.  , 18.  , 21.  , 32.  , 25.  , 58.  , 50.  ,
       30.  , 47.  , 24.  , 20.  , 21.  , 25.  , 20.  ,  4.  , 31.  ,
       24.  , 31.  , 19.  , 20.  , 18.  , 16.  , 35.  , 27.  , 20.  ,
        1.  , 60.  , 25.  ,  1.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,
       30.  , 62.  , 28.  , 20.  , 49.  , 19.  , 18.  , 35.  , 14.5 ,
       25.  , 18.  , 34.  , 45.  , 35.  , 22.  , 24.  , 48.  , 29.  ,
       25.  , 19.  , 18.  , 17.  , 19.  ,  6.  , 17.  , 25.  , 25.  ,
       27.  , 17.  , 30.  , 34.  , 23.  , 15.  , 11.  , 25.  , 25.  ,
       21.  ,  9.  , 35.  , 36.  , 18.  , 21.  , 20.  , 70.  , 16.  ,
       32.  , 19.  , 40.5 ,  4.  ,  6.  , 28.  , 28.  , 24.  ,  0.67,
       18.  , 18.  , 20.  , 16.  , 17.  , 20.  , 14.  , 19.  , 21.  ,
       21.  , 32.  , 28.  , 18.  , 57.  ,  4.  , 40.5 ,  5.  , 15.  ,
       13.  , 17.  , 29.  , 20.  , 22.  , 18.  ,  2.  ,  1.  , 24.  ,
       34.  , 28.  , 25.  , 48.  , 31.  , 17.  , 10.  , 25.  ,  7.  ,
       11.  ,  0.42, 27.  , 19.  , 38.  , 18.  , 25.  , 33.  , 26.  ,
       24.  , 24.  ,  2.  , 20.  , 23.  , 31.  , 43.  ,  4.  , 30.  ,
       27.  , 38.  ,  5.  ,  1.  ,  1.  , 38.  , 15.  ,  0.83, 18.  ,
       18.  , 24.  , 17.  , 32.  , 21.  , 24.  , 30.  , 34.5 , 17.  ,
       42.  , 28.  , 28.  ,  4.  , 19.  ,  9.  , 16.  , 26.  , 18.  ,
       31.  , 34.  ,  0.75, 41.  , 18.  , 48.  , 25.  , 32.  , 27.  ,
       31.  ,  4.  , 28.  , 47.  , 33.  , 22.  , 28.  , 15.  , 20.  ,
       28.  , 24.  , 29.  , 28.  , 22.  , 24.  , 20.  , 39.  , 25.  ,
       19.  , 26.  , 40.5 ])

In [11]:
j = 0
for i in pos_missing_train:
    data['Age'][i] = class_result[j]
    j+=1

display(data)

/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]
/tmp/ipykernel_23095/3587063335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'][i] = class_result[j]

        Sex   Age  Pclass     Fare  Survived
0      male  22.0       3   7.2500         0
1    female  38.0       1  71.2833         1
2    female  26.0       3   7.9250         1
3    female  35.0       1  53.1000         1
4      male  35.0       3   8.0500         0
..      ...   ...     ...      ...       ...
886    male  27.0       2  13.0000         0
887  female  19.0       1  30.0000         1
888  female  24.0       3  23.4500         0
889    male  26.0       1  30.0000         1
890    male  32.0       3   7.7500         0

[891 rows x 5 columns]